- name: printed varibles from prompt level
  hosts: mongodb
  vars_prompt:
  - name: USERNAME
    prompt: Please Enter Userame
    private: false
  - name: PASSWORD
    prompt: Please Enter Password
    private: true
  tasks:
  - name: printed varibles from prompt level
    ansible.builtin.debug:
     msg: "username {{USERNAME}} password {{PASSWORD}}"