- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exists or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: print the command output
    ansible.builtin.debug:
     msg: "output is {{output}}"

  - name: craete user
    ansible.builtin.user:
     name: roboshop
    when: output.rc !== 0 