- name: craete user ramki
  hosts: localhost
  tasks:
  - name: checking user exists or not
    ansible.builtin.command: id ramki
    register: output
    ignore_errors: true
  
  - name: printed command line status
    ansible.builtin.debug:
     msg: "output is {{output}}"

  - name: printed exit status
    ansible.builtin.debug:
     msg: "{{output.rc}}"
  - name: create user ramki
    ansible.builtin.user: 
     name: ramki
    when: output.rc != 0
