- name: install mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copy code from mongod.repo to mongodb
    ansible.builtin.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb
    ansible.builtin.yum:
     name: mongodb-org
     state: installed
  - name: start and enable mongodb
    ansible.builtin.service:
     name: mongod
     state: started
     enabled: yes
  - name: enable remote connections to mongodb
    ansible.builtin.lineinfile:
     path: /etc/mongod.conf
     regexp: '127.0.0.1'
     line: '0.0.0.0'
  - name: restart mongodb
    ansible.builtin.servie:
     name: mongod
     state: restarted